language: python
python:
#  - "2.6"
  - "2.7"

install:
#  - "pip install ."
#  - "pip install -r requirements.txt"
  - pip install pep8
# command to run tests

script: 
 - pep8 ./server/ --ignore=E402
 - nosetests
